"""
pipeline/comment_poster.py

Posts generated comments back to Dev.to articles via the official Dev.to API.
Requires a Dev.to API key set as environment variable: DEVTO_API_KEY

DISCLOSURE REQUIREMENT (Dev.to policy):
  - Your Dev.to profile must be labelled as a bot/automated account.
  - Every posted comment includes a disclosure footer.
  - Dev.to API docs: https://developers.forem.com/api/v1#tag/comments/operation/createComment

How to get your API key:
  1. Log in to Dev.to
  2. Go to Settings → Extensions → DEV API Keys
  3. Generate a new key and set: export DEVTO_API_KEY="your_key_here"

IMPORTANT — Before running:
  Update your Dev.to profile bio to include something like:
  "🤖 Bot account — automated comments posted by CT-377 DM pipeline (NED UET)"
"""

import os
import time
import json
import re
import requests
import pandas as pd

DEVTO_API_KEY = "pHPQZaomhCe12bBGWiU1bRn3"
DEVTO_COMMENTS_URL = "https://dev.to/api/comments"

DISCLOSURE_FOOTER = (
    "\n\n---\n"
    "*🤖 This comment was generated by an automated analysis pipeline "
    "(CT-377 Data Mining Project, NED UET). "
    "Posted via the Dev.to API with bot disclosure as required by Dev.to guidelines.*"
)


def extract_devto_article_id(url: str) -> str | None:
    """
    Extract the numeric article ID from a Dev.to article URL.
    Dev.to article URLs look like: https://dev.to/username/article-slug-XXXXX
    The last segment often ends with a numeric ID, or we fetch it via API.
    """
    # Try slug-based lookup via API
    try:
        # URL pattern: https://dev.to/author/article-title-12345
        # We can query the article by its path
        path = url.replace("https://dev.to/", "").replace("http://dev.to/", "").strip("/")
        headers = {"api-key": DEVTO_API_KEY, "Content-Type": "application/json"}
        r = requests.get(
            f"https://dev.to/api/articles/{path}",
            headers=headers, timeout=10
        )
        if r.status_code == 200:
            return str(r.json().get("id", ""))
    except Exception:
        pass

    # Fallback: extract trailing number from slug if present
    match = re.search(r"-(\d+)$", url.rstrip("/").split("/")[-1])
    if match:
        return match.group(1)

    return None


def post_comment_to_devto(article_id: str, comment_body: str) -> dict:
    """
    Post a single comment to a Dev.to article.
    Returns the API response dict.
    """
    if not DEVTO_API_KEY:
        return {"success": False, "error": "DEVTO_API_KEY not set"}

    full_comment = comment_body + DISCLOSURE_FOOTER

    headers = {
        "api-key": DEVTO_API_KEY,
        "Content-Type": "application/json",
    }
    payload = {
        "comment": {
            "body_markdown": full_comment,
            "commentable_id": int(article_id),
            "commentable_type": "Article",
        }
    }

    try:
        r = requests.post(DEVTO_COMMENTS_URL, headers=headers, json=payload, timeout=15)
        if r.status_code in (200, 201):
            data = r.json()
            return {
                "success": True,
                "comment_id": data.get("id_code", ""),
                "url": f"https://dev.to/comment/{data.get('id_code', '')}",
                "status_code": r.status_code,
            }
        else:
            return {
                "success": False,
                "status_code": r.status_code,
                "error": r.text[:300],
            }
    except requests.RequestException as e:
        return {"success": False, "error": str(e)}


def post_comments(blogs: list, logger=None) -> list:
    """
    For every blog that:
      1. Comes from Dev.to (only platform with public comment API)
      2. Has a generated comment
      3. Has not already been posted (idempotency check via logs)

    Posts the comment and records the result.
    """
    if not DEVTO_API_KEY:
        print("  [Poster] DEVTO_API_KEY not set — skipping comment posting.")
        print("  [Poster] Set it with: export DEVTO_API_KEY='your_key_here'")
        return blogs

    devto_blogs = [b for b in blogs if b.get("source", "").lower() == "dev.to"
                   and b.get("generated_comment", "").strip()
                   and b.get("url", "")]

    if not devto_blogs:
        print("  [Poster] No Dev.to blogs with generated comments found — nothing to post.")
        return blogs

    print(f"  [Poster] Posting to {len(devto_blogs)} Dev.to article(s)…")
    print("  [Poster] Each comment includes bot disclosure footer as required by Dev.to policy.")

    for i, blog in enumerate(devto_blogs):
        url = blog["url"]
        title = blog.get("title", "")[:60]
        print(f"\n  [{i+1}/{len(devto_blogs)}] '{title}'")
        print(f"    URL: {url}")

        article_id = extract_devto_article_id(url)
        if not article_id:
            result = {"success": False, "error": "Could not resolve article ID from URL"}
            print(f"    ✗ {result['error']}")
        else:
            print(f"    Article ID: {article_id}")
            result = post_comment_to_devto(article_id, blog["generated_comment"])

            if result["success"]:
                print(f"    ✓ Comment posted → {result.get('url', '')}")
            else:
                print(f"    ✗ Failed ({result.get('status_code', 'N/A')}): {result.get('error', '')[:120]}")

        blog["post_result"] = result

        # Respectful rate limiting — 1 post per 3 seconds
        if i < len(devto_blogs) - 1:
            time.sleep(3)

    # Save posting log
    os.makedirs("logs", exist_ok=True)
    posting_log = [
        {
            "title": b.get("title", "")[:80],
            "url": b.get("url", ""),
            "generated_comment": b.get("generated_comment", ""),
            "post_result": b.get("post_result", {}),
        }
        for b in devto_blogs
    ]
    with open("logs/posting_log.json", "w", encoding="utf-8") as f:
        json.dump(posting_log, f, ensure_ascii=False, indent=2)
    print(f"\n  [Poster] Posting log saved → logs/posting_log.json")

    if logger:
        logger.log_phase("comment_posting", {
            "platform": "Dev.to",
            "attempted": len(devto_blogs),
            "succeeded": sum(1 for b in devto_blogs if b.get("post_result", {}).get("success")),
            "disclosure_included": True,
        })

    return blogs
if __name__ == "__main__":
    print("🚀 Running Dev.to Comment Poster...")
    print("Current Directory:", os.getcwd())

    try:
        import pandas as pd

        # STEP 1: load data FIRST
        df = pd.read_csv("DM_2/generated_comment.csv")
        # STEP 2: debug safely
        print("\n📊 CSV PREVIEW:")
        print(df.head())

        print("\n📌 COLUMNS:")
        print(df.columns)

        # STEP 3: convert to dict
        blogs = df.to_dict("records")

        # STEP 4: run poster
        result = post_comments(blogs)

        print("\n✅ Posting finished.")

    except Exception as e:
        print("❌ Error:", e)